=== sugam-hub/WEB-Assignment-1/xml/_2a.dtd
<!ELEMENT Books (Book+)>
<!ELEMENT Book(Name,Author+,Page,Price)>
<!ELEMENT Name(#PCDATA)>
<!ELEMENT Author(Author_Name,Email)>
<!ELEMENT Author_Name(#PCDATA)>
<!ELEMENT Email(#PCDATA)>
<!ELEMENT Page(#PCDATA)>
<!ELEMENT Price(#PCDATA)>
<!ATTLIST Book isbn CDATA #REQUIRED>
<!ATTLIST Price currency(npr|usd) "npr">

=== sugam-hub/WEB-Assignment-1/_2b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Books SYSTEM "_2a.dtd">
<Books>
    <Book isbn="5678">
        <Name>Web Tech</Name>
        <Author>
            <Author_Name>Anish Sharma</Author_Name>
            <Email>anish021@gmail.com</Email>
        </Author>
        <Page>200</Page>
        <Price currency="npr">450</Price>
        </Book>
        <Book isbn="12345">
            <Name>JAVA</Name>
            <Author>
                <Author_Name>Niraj Karki</Author_Name>
                <Email>niraj123@gmail.com</Email>
            </Author>
            <Page>100</Page>
            <Price>400</Price>
        </Book>
</Books>
